--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/GrosserZak/PortableCrates
build-by-default: true
branches:
- main
projects:
  PortableCrates:
    path: ""
    icon: "PortableCrates.gif"
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^4.0.0
        branch: 4.0
...
