name: PortableCrates
src-namespace-prefix: GrosserZak\PortableCrates
main: GrosserZak\PortableCrates\Main
version: 2.1.0
api: 4.0.0
author: GrosserZak
description: Plugin that give carriable crates
permissions:
  portablecrates.command.give:
    description: "Allows the player to give crates"
    default: op
  portablecrates.command.edit:
    description: "Allows the player to edit crates(Create/delete crates, add/remove rewards to crates)"
    default: op

